### ISSUE TITLE
New Issue Downloading MP4 Files

### ISSUE THREAD

**Issue by bhbobby** [khoadng/Boorusama#449] opened 2024-09-16 13:55 UTC
The previous issue seemed to fix itself as it was apparently an issue with the website itself, however I have a new error with downloading video files that only affects video files once again, pictures download fine. Here is the error I am getting with video files:

Download error: PathNotFoundException: Cannot copy file to '/storage/3233-6230/Download/
5353372_c0791b64.mp4', path = '/data/user/0/com.degenk.boourusama/cache/
c0791b641897622c1e5c35f11e175f35.mp4.partial' (OS Error: No such file or directory, errno = 2)

It's not a directory or path issue as this is only affecting video files, image files have no problem saving to the path I set. Thank you

**Comment by bhbobby** [comment] 2024-09-16 15:04
No, it's happening as a single file download as well

**Comment by khoadng** [comment] 2024-09-16 15:40
Are you using the legacy downloader? Go to Settings > Downloads and turn it off to see if the issue is fixed

**Comment by bhbobby** [comment] 2024-09-16 15:41
Legacy downloader is off, I don't think I've ever had it on

**Comment by khoadng** [comment] 2024-09-16 16:26
Try clearing the app’s cache, it looks like the downloaded file might be corrupt.

**Comment by bhbobby** [comment] 2024-09-16 17:02
Where do I go to do that?

**Comment by khoadng** [comment] 2024-09-16 17:08
Settings > Data and Storage. 

If it doesn't work, long press on the app icon. There should be options for you to clear app's cache. 
Don't clear app's data tho, you will lose all of your profiles.

**Comment by bhbobby** [comment] 2024-09-16 19:12
Yeah, it was my device running low on memory, I guess. I cleared some stuff out and it's working again. Sorry, to be such a bother with this stuff.

While I have you here, is there a way to manually set the number of concurrent downloads in bulk downloader?

**Comment by khoadng** [comment] 2024-09-17 02:16
I left it out on purpose to prevent potential abuse. Having tons of current downloads puts a heavy load on the server, and the site owner probably wouldn’t like that

**Comment by bhbobby** [comment] 2024-09-17 12:59
Well, that's the thing. I want to lower the number. I see though, thanks

**Comment by khoadng** [comment] 2024-09-17 13:48
Since the issue is resolved, I will go ahead and close this, feel free to reopen if you still have other concerns.

**Closed by khoadng** 2024-09-17 13:48 UTC
Labels: bug
